name: FiapFoodRabbitMQ - CICD

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  RABBITMQ_USER: "${{secrets.RABBITMQ_USER}}"
  RABBITMQ_PASS: "${{secrets.RABBITMQ_PASS}}"

jobs:
  build-container:
    name: "Build Application Container"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    timeout-minutes: 10
    steps:
      - name: Configure Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            gm50x/rabbitmq-management-delayed:latest
            gm50x/rabbitmq-management-delayed:v3${{ github.run_number }}
  deploy:
    name: "Deploy Application"
    runs-on: ubuntu-latest
    needs: [build-container]
    environment: "production"
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Configure Kubectl
        run: aws eks update-kubeconfig --name fiap-food-k8s

      - name: Configure Secrets
        run: |
          envsubst < k8s/app-secrets.template.yaml > k8s/app.secrets.yaml
          kubectl apply -f k8s/app.secrets.yaml

      - name: Apply K8S
        run: |
          kubectl apply -f k8s/app-deployment.yaml
          kubectl rollout restart deployment/fiap-food-rabbitmq
